### ISSUE TITLE
how to use web-socket?

### ISSUE THREAD

**Issue by wrfly** [turbinelabs/rotor#19]
I didn't find any configurations to set that, can you tell me how to modify the protocol?
The configs only contains host and port (and metadata), maybe the config below is misused, I don't know.  

```yaml
- cluster: jenkins.102.co
  instances:
    - host: 10.6.8.102
      port: 8082
      metadata:
        - key: envoy.lb
          value: canary
        - key: use_websocket
          value: true
        - key: service_name
          value: jnkins.102.com
```

And I found that the listenner's config always set to
```go
var (
	xdsClusterConfig = envoycore.ConfigSource{
		ConfigSourceSpecifier: &envoycore.ConfigSource_ApiConfigSource{
			ApiConfigSource: &envoycore.ApiConfigSource{
				ApiType:      envoycore.ApiConfigSource_GRPC,
				ClusterNames: []string{xdsClusterName},
				RefreshDelay: ptr.Duration(xdsRefreshDelaySecs * time.Second),
			},
		},
	}
)
```

I stuck in this for a whole day, help me out please....

Thank you...

**Comment by 9len** [comment]
Do all your clusters need this, or just some?

Depending on the answer, you can specify either a `cluster_template`or a few fixed `clusters` in a YAML file using the `-xds.static_resources_filename` flag, or the `ROTOR_XDS_STATIC_RESOURCES_FILENAME` env var.

**Comment by wrfly** [comment]
Some clusters need this, not all.
You mean put the `xds.static_resources_filename` in metadata filed, like this?
```yaml
- cluster: jenkins.102.co
  instances:
    - host: 10.6.8.102
      port: 8082
      metadata:
        - key: xds.static_resources_filename
          value: ???
```
There are not much documentation about how to write that. I looked up the source code and found that the yaml file only support these five keys: `cluster`, `instances`, `host`, `port` and `metadata`. Actually I don't know which part does the `-xds.static_resources_filename` flag belongs to...

Would you mind give me an example? Thank you very much!

**Comment by 9len** [comment]
Rotor is intended primarily as a simple envoy->EDS bridge, and as the control-plane for our commercial product. 

There are many different collector plugins, we chose not to implement specific configuration in any og them beyond host/port and metadata. Instead, we provide a facility to statically specify clusters and listeners at rotor startup, using _envoy_ configuration. 

If you're running the docker image, you would specify a filename as an env var (`ROTOR_XDS_STATIC_RESOURCES_FILENAME: <some path>`, and you'd need to mount a YAML file at that path. 

The YAML file would contain a `clusters` array, where each entry is an [envoy v2 cluster object](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto) corresponding to the cluster you want to configure. If you make this cluster type EDS, and specify an `eds_cluster_config` pointing back to `tbn-xds`, the collector should use whatever hosts it collects but with the cluster config you specify.

**Comment by wrfly** [comment]
Okay, thanks for your reply, I'll test it tomorrow!
After it works, maybe I can make a PR of file example :smiley:

**Comment by 9len** [comment]
So it looks like websockets are configured on the [_route_](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction-websocketproxyconfig) rather than the cluster. To do this you'd have to hard code a full [listener](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/lds.proto) in the static resources. 

There's a basic example of this in the [tests](https://github.com/turbinelabs/rotor/blob/master/xds/adapter/static_resources_test.go#L240-L298); you'll need to specify your routes in the listener explicitly.

**Comment by wrfly** [comment]
Hello @9len 
It there a way to modify the default listener configs? Cause I want to add the `use_websocket` config to one of the clusters' `route_config`.`virtual_hosts`, but rotor will ignore the static config since the listener's name is duplicated: `ignoring listener with duplicate name: "bj_vm:80"`

But if I set `ROTOR_XDS_STATIC_RESOURCES_CONFLICT_BEHAVIOR=overwrite`, the configs I set will be overwrited with the auto-generated one.

Here is my static config and the docker-compose file:

```yaml
listeners:
- name: bj_vm:80
  address:
    socket_address: { address: 0.0.0.0, port_value: 80 }
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      config:
        stat_prefix: bj_vm-80
        route_config:
          name: bj_vm:80
          virtual_hosts:
          - name: tty.102.co-80
            domains: ["tty.102.co"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: tbn-xds, use_websocket: true }
        http_filters:
        - name: envoy.cors
          config: {}
        rds:
          config_source:
            api_config_source:
              api_type: GRPC
              cluster_names:
                - tbn-xds
              refresh_delay: 30.000s
          route_config_name: 'bj_vm:80'
```

```yaml
version: "2"
services:
  envoy:
    image: turbinelabs/envoy-simple:0.18.0
    ports:
      - 80:80
      - 81:81
      - 9999:9999
    environment:
      - ENVOY_XDS_HOST=10.6.8.102
      - PORT=80:80
      - PORT=9999:9999
      - ENVOY_NODE_CLUSTER=bj_vm
      - ENVOY_NODE_ZONE=test_zone

  rotor:
    image: turbinelabs/rotor:0.18.0
    ports:
      - 50000:50000
    environment:
      - ROTOR_CONSOLE_LEVEL=debug
      - ROTOR_CMD=file
      - ROTOR_FILE_FORMAT=yaml
      - ROTOR_FILE_FILENAME=/data/routes.yml
#      - ROTOR_CMD=consul
      - ROTOR_CONSUL_DC=bj_office
      - ROTOR_CONSUL_HOSTPORT=10.6.8.102:8500
      - ROTOR_XDS_RESOLVE_DNS=true
      - ROTOR_XDS_STANDALONE_CLUSTER=bj_vm
      - ROTOR_XDS_STANDALONE_ZONE=test_zone
      - ROTOR_CONSUL_CLUSTER_TAG=test
      - ROTOR_XDS_STATIC_RESOURCES_CONFLICT_BEHAVIOR=overwrite
      - ROTOR_XDS_STATIC_RESOURCES_FILENAME=/data/static_resources.yml
    volumes:
      - ./data:/data
```

and the routes:

```yaml
- cluster: crek.102.co
  instances:
    - host: 10.6.8.102
      port: 8080
- cluster: jenkins.102.co
  instances:
    - host: 10.6.8.102
      port: 8082
- cluster: ftp.102.co
  instances:
    - host: 10.6.8.102
      port: 8091
- cluster: tty.102.co
  instances:
    - host: 10.6.8.102
      port: 5082
```

How can I set the `tty.102.co` to use websocket? Is there a workaround?

I tried to add another listener to listen the port 81, and I can see the static routes in `/config_dump`, but envoy didn't return any data after **18:29:49.094901**:

```txt
root@vmwareserver02:~/components/rotor_and_envoy/data# tcpdump -n -i any src 172.29.0.3 or port 5082
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
18:29:49.094592 IP 172.29.0.3.81 > 172.29.0.1.51920: Flags [S.], seq 2808129362, ack 357772550, win 28960, options [mss 1460,sackOK,TS val 1444472167 ecr 4067835498,nop,wscale 7], length 0
18:29:49.094592 IP 172.29.0.3.81 > 172.29.0.1.51920: Flags [S.], seq 2808129362, ack 357772550, win 28960, options [mss 1460,sackOK,TS val 1444472167 ecr 4067835498,nop,wscale 7], length 0
18:29:49.094901 IP 172.29.0.3.81 > 172.29.0.1.51920: Flags [.], ack 76, win 227, options [nop,nop,TS val 1444472168 ecr 4067835499], length 0
18:29:49.094901 IP 172.29.0.3.81 > 172.29.0.1.51920: Flags [.], ack 76, win 227, options [nop,nop,TS val 1444472168 ecr 4067835499], length 0
18:29:57.636037 IP 172.29.0.3.9999 > 10.6.5.136.60439: Flags [S.], seq 2775224961, ack 1702054583, win 28960, options [mss 1460,sackOK,TS val 1228173930 ecr 1060512827,nop,wscale 7], length 0
18:29:57.636037 IP 172.29.0.3.9999 > 10.6.5.136.60439: Flags [S.], seq 2775224961, ack 1702054583, win 28960, options [mss 1460,sackOK,TS val 1228173930 ecr 1060512827,nop,wscale 7], length 0
```

Is there a way to combine the listeners or the clusters with the static resources and the xds-generated one? The API definitions is soooo complicated....

**Comment by 9len** [comment]
Unfortunately, you've bumped up against the edge of what Rotor can support. Because listener configs can be pretty exotic, it's non-trivial to merge them together when they collide on the same port.

your two options are:

1) listen on a different port, as you have here
2) add all the other routes for your other services to your static listener config, and set `ROTOR_XDS_STATIC_RESOURCES_CONFLICT_BEHAVIOR=overwrite`

For 1) you may need to remove the `rds` section from your static listener if you haven't already; it may be that when you specify `rds`, the fixed routes are ignored. 

For 2) it may be useful to run the `rotor-test-client` binary within the running rotor docker container; it will give you the full dump of the generated listener.

In either case, you may want to check the [websockets documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/websocket), and it may be helpful to run your envoy with `-l trace` so you get a full log of every request.

**Comment by wrfly** [comment]
Finally.....

```yaml
clusters:
- name: tty-stadic
  type: STATIC
  connect_timeout: 10s
  lb_policy: LEAST_REQUEST
  hosts:
  - socket_address:
      address: 10.6.8.102
      port_value: 5082

listeners:
- name: 'bj_vm:80'
  address:
    socketAddress:
      address: 0.0.0.0
      portValue: 80
  filterChains:
    -
      filterChainMatch: {}
      filters:
        -
          name: envoy.http_connection_manager
          config:
            access_log:
              -
                config:
                  additional_request_headers_to_log:
                    - X-TBN-DOMAIN
                    - X-TBN-ROUTE
                    - X-TBN-RULE
                    - X-TBN-SHARED-RULES
                    - X-TBN-CONSTRAINT
                  common_config:
                    grpc_service:
                      envoy_grpc:
                        cluster_name: tbn-xds
                    log_name: tbn.access
                name: envoy.http_grpc_access_log
            http_filters:
              -
                config: {}
                name: envoy.cors
              -
                config:
                  upstream_log:
                    -
                      config:
                        additional_request_headers_to_log:
                          - X-TBN-DOMAIN
                          - X-TBN-ROUTE
                          - X-TBN-RULE
                          - X-TBN-SHARED-RULES
                          - X-TBN-CONSTRAINT
                        common_config:
                          grpc_service:
                            envoy_grpc:
                              cluster_name: tbn-xds
                          log_name: tbn.upstream
                      name: envoy.http_grpc_access_log
                name: envoy.router
            route_config:
              name: "route-config"
              virtual_hosts:
                - name: "tty.102.co-80"
                  domains: ["tty.102.co"]
                  routes:
                    - match:
                        prefix: "/"
                        case_sensitive: false
                      route:
                        cluster: "tty-stadic"
                        use_websocket: true
                        websocket_config:
                          stat_prefix: "/"
            stat_prefix: bj_vm-80
```

And the compose file:

```yaml
version: "2"
services:
  envoy:
    image: turbinelabs/envoy-simple:0.18.0
    ports:
      - 80:80
      - 81:81
      - 9999:9999
    environment:
      - ENVOY_XDS_HOST=10.6.8.102
      - PORT=80:80
      - PORT=9999:9999
      - ENVOY_NODE_CLUSTER=bj_vm
      - ENVOY_NODE_ZONE=test_zone
      - ENVOY_ARGS=-l trace

  rotor:
    image: turbinelabs/rotor:0.18.0
    ports:
      - 50000:50000
    environment:
      - ROTOR_CONSOLE_LEVEL=debug
      - ROTOR_CMD=file
      - ROTOR_FILE_FORMAT=yaml
      - ROTOR_FILE_FILENAME=/data/routes.yml
      - ROTOR_XDS_RESOLVE_DNS=true
      - ROTOR_XDS_STANDALONE_CLUSTER=bj_vm
      - ROTOR_XDS_STANDALONE_ZONE=test_zone
      - ROTOR_XDS_STANDALONE_PORT=81
      - ROTOR_CONSUL_CLUSTER_TAG=test
      - ROTOR_XDS_STATIC_RESOURCES_FILENAME=/data/static_resources.yml
    volumes:
      - ./data:/data
```

Thanks for your patience @9len , it works!

I still have to say, the config of envoy is soooooo complicated and confusing and annoying, and `rotor` is a great project, thank you!
