### ISSUE TITLE
How to route to my defined clusters in rotor file mode configuration

### ISSUE THREAD

**Issue by mehdihadeli** [turbinelabs/rotor#31]
Hi, 
@9len I want to use `rotor file mode` configuration, this is my configurations:

clusters.yaml
``` yaml
- cluster: example-cluster-1
  instances:
    - host: 172.27.71.209
      port: 8002
    - host: 172.27.71.209
      port: 8001
- cluster: example-cluster-2
  instances:
    - host: 172.27.71.209
      port: 8002
```

my docker run commands :

``` bash
docker run --name hello-world1 -d -p 8001:80 containersol/hello-world
docker run --name hello-world2 -d -p 8002:80 containersol/hello-world
```

``` bash
docker run -v $(pwd)/:/data    \
  -e 'ROTOR_CMD=file' \
  -e 'ROTOR_CONSOLE_LEVEL=debug' \
  -e 'ROTOR_FILE_FORMAT=yaml' \
  -e 'ROTOR_FILE_FILENAME=/data/clusters.yaml' \
  -p 50000:50000 \
  turbinelabs/rotor:0.19.0
```

``` bash
docker run \
  -e 'ENVOY_XDS_HOST=172.27.71.209' \
  -e 'ENVOY_XDS_PORT=50000' \
  -p 9999:9999 \
  -p 80:80 \
  turbinelabs/envoy-simple:0.19.0
```

Now, when I do a curl request with `curl localhost:80` I didn't get any response from my hello world container!!
Also if I want to customize the route to serve each cluster in different routes, what do I do?
